# Generated by Django 3.1.5 on 2021-03-02 16:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Тема')),
                ('text_blog', models.TextField(verbose_name='Описание')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
            },
        ),
        migrations.CreateModel(
            name='Bloger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('age', models.PositiveIntegerField(verbose_name='Возвраст')),
                ('about', models.TextField(blank=True, null=True, verbose_name='Инфо')),
            ],
            options={
                'verbose_name': 'Блоггер',
                'verbose_name_plural': 'Блоггеры',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comments', models.TextField(verbose_name='Комментарий')),
                ('author_comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogdiy.bloger')),
                ('to_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogdiy.blog')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='author_blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogdiy.bloger', verbose_name='Автор'),
        ),
    ]
