# Generated by Django 3.1.5 on 2021-03-02 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogdiy', '0002_auto_20210302_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date_comment',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
