# Generated by Django 3.1.5 on 2021-03-02 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogdiy', '0005_auto_20210302_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='author_comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='to_blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogdiy.blog', verbose_name='Для статьи'),
        ),
    ]
