# Generated by Django 3.1.5 on 2021-03-11 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogdiy', '0007_auto_20210306_2016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-date_comment'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_a_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogdiy.blog', verbose_name='Понравилось')),
                ('who', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Понравилось',
                'verbose_name_plural': 'Понравились',
            },
        ),
    ]
