# Generated by Django 3.1.5 on 2021-03-11 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogdiy', '0010_auto_20210311_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='likes',
            field=models.CharField(default=0, max_length=200, verbose_name='<django.db.models.fields.related.ForeignKey>_<django.db.models.fields.related.ForeignKey>'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='like',
            name='what_a_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogdiy.blog', verbose_name='Блог'),
        ),
        migrations.AlterField(
            model_name='like',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Блоггер'),
        ),
    ]
