# Generated by Django 3.1.5 on 2021-03-12 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogdiy', '0013_like_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
