# Generated by Django 3.1.5 on 2021-03-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdiy', '0015_bloger_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloger',
            name='foto',
            field=models.ImageField(default='foto-users/adm1.png', upload_to='foto-users/', verbose_name='Фото профиля'),
        ),
    ]
