# Generated by Django 3.1.5 on 2021-03-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdiy', '0017_auto_20210313_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloger',
            name='foto',
            field=models.ImageField(default='nophoto/nofoto.png', upload_to='users/', verbose_name='Фото профиля'),
        ),
    ]
