# Generated by Django 3.1.5 on 2021-03-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdiy', '0018_auto_20210313_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloger',
            name='foto',
            field=models.ImageField(default='foto-users/nofoto.png', upload_to='foto-users/', verbose_name='Фото профиля'),
        ),
    ]
