# Generated by Django 3.1.5 on 2021-03-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdiy', '0020_remove_bloger_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloger',
            name='foto',
            field=models.ImageField(default='foto-users/nofoto.png', upload_to='foto-users/', verbose_name='Фото профиля'),
        ),
    ]
