# Generated by Django 3.1.5 on 2021-04-01 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdiy', '0021_bloger_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='picture_blog',
            field=models.ImageField(default=1, upload_to='photo_blog/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
