# Generated by Django 3.1.5 on 2021-04-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdiy', '0023_auto_20210404_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='picture_blog',
            field=models.ImageField(default='photo_blog/no-foto.gif', upload_to='photo_blog/', verbose_name='Изображение'),
        ),
    ]
