# Generated by Django 3.1.5 on 2021-04-05 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogdiy', '0024_auto_20210404_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaitingVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.SmallIntegerField(default=0, verbose_name='Значение рейтинга')),
            ],
            options={
                'verbose_name': 'Значение рейтинга',
                'verbose_name_plural': 'Значение рейтинга',
            },
        ),
        migrations.CreateModel(
            name='Raiting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogdiy.blog', verbose_name='Какой блог')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogdiy.raitingval', verbose_name='Значение')),
                ('who_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто')),
            ],
            options={
                'verbose_name': 'Рейтинг блога',
                'verbose_name_plural': 'Рейтинг блога',
            },
        ),
    ]
