# Generated by Django 3.1.5 on 2021-04-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdiy', '0025_raiting_raitingval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raitingval',
            name='val',
            field=models.SmallIntegerField(default=1, verbose_name='Значение рейтинга'),
        ),
    ]
