# Generated by Django 3.1.5 on 2021-04-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdiy', '0026_auto_20210406_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raitingval',
            name='val',
            field=models.SmallIntegerField(default=0, verbose_name='Значение рейтинга'),
        ),
    ]
