# Generated by Django 3.1.5 on 2021-04-06 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogdiy', '0027_auto_20210406_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raiting',
            name='value',
        ),
    ]
