# Generated by Django 3.1.5 on 2021-04-30 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogdiy', '0028_remove_raiting_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RaitingVal',
        ),
    ]
