# Generated by Django 3.1.5 on 2021-05-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogdiy', '0030_auto_20210516_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloger',
            old_name='name_ua',
            new_name='name_uk',
        ),
        migrations.RenameField(
            model_name='bloger',
            old_name='surname_ua',
            new_name='surname_uk',
        ),
    ]
