# Generated by Django 3.1.5 on 2021-03-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagesusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesbetweenusers',
            name='text_message',
            field=models.TextField(verbose_name='Текст сообщения'),
        ),
    ]
