# Generated by Django 3.1.5 on 2021-03-18 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagesusers', '0003_auto_20210318_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagesbetweenusers',
            name='dialog',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
