# Generated by Django 3.1.5 on 2021-03-31 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messagesusers', '0004_auto_20210318_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesbetweenusers',
            name='addressee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_addressee', to=settings.AUTH_USER_MODEL, verbose_name='Получатель(выберите из списка)'),
        ),
    ]
