# Generated by Django 3.1.5 on 2021-05-02 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagesusers', '0005_auto_20210331_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagesbetweenusers',
            options={'ordering': ['-date_message'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
